// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXWViJJmUrcRPEXzrycsro4xNIHrkY36A',
    appId: '1:745925268663:web:0b5d218045064f08a7a932',
    messagingSenderId: '745925268663',
    projectId: 'lepachat',
    authDomain: 'lepachat.firebaseapp.com',
    storageBucket: 'lepachat.firebasestorage.app',
    measurementId: 'G-YLB7WDP927',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA3tnkEd3FGDeK17G7dm-gqeEtpt10WUA',
    appId: '1:745925268663:android:2243129ce28b55caa7a932',
    messagingSenderId: '745925268663',
    projectId: 'lepachat',
    storageBucket: 'lepachat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8KEMSZaAYalbtYKbzBrYxQeduq-hOINg',
    appId: '1:745925268663:ios:045dc90998549b51a7a932',
    messagingSenderId: '745925268663',
    projectId: 'lepachat',
    storageBucket: 'lepachat.firebasestorage.app',
    iosBundleId: 'com.example.lepa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8KEMSZaAYalbtYKbzBrYxQeduq-hOINg',
    appId: '1:745925268663:ios:045dc90998549b51a7a932',
    messagingSenderId: '745925268663',
    projectId: 'lepachat',
    storageBucket: 'lepachat.firebasestorage.app',
    iosBundleId: 'com.example.lepa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXWViJJmUrcRPEXzrycsro4xNIHrkY36A',
    appId: '1:745925268663:web:c46b5adc06c53be9a7a932',
    messagingSenderId: '745925268663',
    projectId: 'lepachat',
    authDomain: 'lepachat.firebaseapp.com',
    storageBucket: 'lepachat.firebasestorage.app',
    measurementId: 'G-EM5F4KSBPS',
  );
}
